# Generated by Django 4.2.17 on 2024-12-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="name", new_name="subject",
        ),
        migrations.AddField(
            model_name="course",
            name="campus",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="catalog_number",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="topic",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
