# Generated by Django 4.2.17 on 2024-12-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_rename_name_course_subject_course_campus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="public",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
